global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Spectre.Console;
global using LizzysIcecreamShop.HR;
global using LizzysIcecreamShop;
global using System.Text.RegularExpressions;